runtime: java11
service: guestbook-service
instance_class: B4_1G
manual_scaling:
  instances: 2
env_variables:
  SPRING_PROFILES_ACTIVE: cloud
vpc_access_connector:
  name: "projects/microservicesapp-300213/locations/us-central1/connectors/sql-connector"